### ISSUE TITLE
Customizable menu collapse

### ISSUE THREAD

**Issue by naasking** [franciscop/picnic#125]
It seems the navigation menu collapses into a hamburger at a fixed breakpoint no matter the content. It would be nice if this breakpoint could adapt to the consumed width, but that's probably too ambitious, so being able to manually specify would suffice. Something like:

    <nav class="demo">
      <a href="#" class="brand">Picnic CSS</a>
      
      <input id="bmenug" type="checkbox" class="show">
      <label for="bmenug" class="burger pseudo button">&#8801;</label>

      <div class="menu collapse-800">
        <input placeholder="Search plugins" />
      </div>
    </nav>

**Comment by franciscop** [comment]
I had this in mind but didn't get around to implement it. I also worry about the file size because there's a lot of logic inside the `@media` query there (I hope that [gzip does it thing](https://medium.com/@fpresencia/understanding-gzip-size-836c74b66c0b) though).

Do you want to give it a shot, @naasking ? Otherwise I'll leave this open for when I have a while, but this is not a priority right now for me since [it uses `$picnic-breakpoint`](https://github.com/picnicss/picnic/blob/master/src/plugins/nav/_plugin.scss#L13) and I mostly use SASS these days where I can modify that or I'm happy with the default one.

**Comment by naasking** [comment]
I might if I decide to go with Picnic for my project. Right now I'm still exploring the various options, like mini.css and Picnic, and providing some feedback where I've run into legit uses that are missing or could be enhanced somehow.

Thanks for the cool project!

**Comment by EthraZa** [comment]
I guess I'm facing this problem now.
I added a bunch of buttons to the nav menu and instead of getting the hamburger button it got broken.
There is a way to get the burger menu all the time?

[Screenshot of the Problem](https://drive.google.com/file/d/0Bx9-WHdL_i7iTlR3Y0JqdGJpNVU/view)

**Comment by franciscop** [comment]
I see I never replied to this, but this has been fixed for a while if you are using the SCSS:

```scss
$picnic-breakpoint: 60em;

@import 'PATH_TO_PICNIC';
```

I have thought about making it like the grid system, so specific breakpoints can be added as a class:

```html
<!-- not implemented now: -->
<nav class="burger-800">...</nav>
```

However I cannot give any estimate on whether or not this last bit will be implemented at all.
