### ISSUE TITLE
Problem with <nav> styling conflicting with other things using the <nav> element (v6.2.5)

### ISSUE THREAD

**Issue by nmcgann** [franciscop/picnic#128]
This is in particular when using Picnic 6.2.5 and Alertify v1.07 JS to provide dialogs/popups.

Alertify uses the `<nav>` element within its dialogs to enclose buttons, but Picnic does not qualify the use of `<nav>` with a more specific selector to restrict it to the top nav so it overrides the styling of the dialogs `<nav>`.

Would be sensible to have `#top-menu nav` or similar in the CSS to make it a little more specific.

(I temporarily fixed the problem for myself by editing the Alertify JS and CSS to use normal `<div>` elements instead of `<nav>`)

**Comment by franciscop** [comment]
Hi @nmcgann thanks for pointing that out. I am not sure whether they follow the NAV specification since the way they are using it could hardly be called a "*major navigation blocks*" or even a "*a section of a page that links to other pages or to parts within the page*", as those are not linking anywhere but are just action buttons:

> http://html5doctor.com/nav-element/

There are few options for solving this with Picnic CSS, are you using the CSS or the SASS version?

What you point out is unfortunately the main disadvantage of Picnic CSS but it's part of a design decision: to make some elements have styles by default. This makes it great for small/medium projects but difficult for medium/large projects with many moving parts. It means that you can drop Picnic CSS in many projects and it works by default, but it's difficult to make it work with some other libraries.

**Comment by nmcgann** [comment]
Yes, it's not really a nav as such - maybe an example of getting a bit over-keen with html5 for the sake of it. There are very few non-blocking dialog/message systems that don't rely on jquery though, so I had to persist and make it work.

I'm using CSS.

I think the design decisions are great - I'm a JS+php dev really so getting a CSS framework that looks good without much graphical design skill is a big win.

**Comment by RyanZim** [comment]
A hearty +1 to this. I generally agree that auto-styling elements is good. However, in the case of `<nav>`, I feel it's different. There are many valid ways to style a nav, of which a top bar is one good way.

In my case, I have too many menu items to fit in the top bar format. My current workaround is to use `<div role="navigation">` instead of `<nav>`, but that seems hacky.

**Comment by franciscop** [comment]
If you are using the scss you can easily modify this by copy/pasting the [main SCSS file](https://github.com/franciscop/picnic/blob/master/src/picnic.scss), changing the paths accordingly and removing the nav bit. Otherwise there's no intention to modify Picnic CSS to allow for this as explained.
