### ISSUE TITLE
Unintuitive Grid

### ISSUE THREAD

**Issue by chmln** [franciscop/picnic#143]
Hello,

First of all I'd like to say that I absolutely love picnic!
Most of all I love how button effects are done and the ease of adding new colors.

Anyways.

Perhaps this is somewhat subjective, but I find its hard to reason about the following grid style:
```html
<div class="full half-500 third-800"><span>3</span></div>
```
Some examples are much more straightforward, like `flex three`, but I think the grid could be even better and simpler.

[Here's a remarkably simple and lightweight flex grid](http://www.meetsally.com/).
The [source code](http://www.meetsally.com/sally.sass) is lovely, also.

Its what I use on nearly all my production apps, and I believe that for 99% of cases there isn't a need for something as complex as the current implementation.

Thank you for the attention :cactus:

**Comment by franciscop** [comment]
For non-responsive sites the `flex three` example is enough. But most people expect to use a *responsive* grid system, so the system works like this for the container/row/parent:

- `flex`: will space them automatically side by side
- `flex three`: will set up three elements of 33.3% width each
- `flex two three-600`: will set up two elements and three for screens with a width larger than 600px

For the cells/cols/children normally you don't need to do anything if you want them all to behave the same way (as the one that you linked). The classes you showed were for whenever you want them with different sizes.

The one you linked is similar for this case, it just uses keywords instead of breakpoint sizes. The problem is that there's a choice between *simple* (and not flexible) or fully featured (but difficult). The initial grid in Picnic was a lot like the one you linked, but now it is *really* flexible with the added complexity.
