### ISSUE TITLE
Small glitch when clicking on a radio input

### ISSUE THREAD

**Issue by JulienJo** [franciscop/picnic#146]
Hi, 
I noticed a strange thing when I click to a radio button (at least on chrome). It seem's to be caused by the transform and the transition. If you disabled transition, you would not see this glitch anymore.
cheers!

**Comment by franciscop** [comment]
Could you describe the glitch please?

**Comment by JulienJo** [comment]
well... on Firefox and IE11, the `label::after` seem's to not be really round. 
On chrome (V.58.0.3029.110 (64-bit)) when I click on a radio button, the `label::after` twinkles a little.

**Comment by franciscop** [comment]
That is strange, I am in `Version 58.0.3029.81 (64-bit)` and it works exactly as intended and in fact Chrome is the one that behaves best for me. This is how it's intended (ignore conversion artifacts):

![radio](https://cloud.githubusercontent.com/assets/2801252/26595314/42f61298-456b-11e7-9a4b-cd0fe3201ce5.gif)

With firefox/others, at certain sizes it does become not-round, unfortunately I think it's an engine bug [as border-radius has a troubled past](http://lea.verou.me/2010/10/the-curious-case-of-border-radius50/) that happens only at certain resolutions. I think with fixed `px` sizing the issue is less noticeable/gone, so I'll leave this open for whenever I can fix it.
