### ISSUE TITLE
Variables for fonts

### ISSUE THREAD

**Issue by Frenzel** [franciscop/picnic#161]
I'm starting a new project with Picnic. Seems a very good framework for my needs. Minimalistic but not too bare-bone. So I'm starting to setup the default variables.

There are no variables for font settings. So there is no way to set my own font except some nasty overwrite with a more specific class or id or modifying picnic itself, which IMHO defies the goal of having a framework. 

Is this done for a reason or am I missing something?

**Comment by franciscop** [comment]
They are defined here: https://github.com/franciscop/picnic/blob/master/src/plugins/generic/_plugin.scss

So just changing the font of the `body` should do the trick. In other places (where needed) they follow the `font: inherit;` as much as possible, so they should be taken properly.

**Comment by Frenzel** [comment]
Sure but then I'll be modifying the framework itself and not making use overwriting options. Why then defining variables in the first place? Aren't they for the most common things you want to change without hacking the framework itself?

**Comment by franciscop** [comment]
But you *are* making use of the best overwriting option in CSS and part of it's core characteristic: cascading.

Variables are defined so you can chance things in many places within a single place. It is all about repetition:

- To change the font in every place you have to change it once on the body.
- To change the border-radius everywhere you have to change it in a variable. Same with colors, transitions, etc.

This is because border-radius will be applied independently in many places, and trying to change it manually in CSS would lead you into many small overwrites. These properties have variables to avoid this. However with some properties you can just overwrite them once and it will work properly.

The framework *is* designed for this use-case as much as possible. Font size will lead to automatically adjusted paddings in buttons (with `em` ), for instance.

**Comment by franciscop** [comment]
If it wasn't clear (sorry), I mean to overwrite the body font in your own CSS, not to clone the whole repo and change it inside Picnic's code:

```html
<link src="picnic.css" ...>
<style>
  body {
    font-fanily: ...;
  }
</style>
```
