### ISSUE TITLE
Divs not showing below nav

### ISSUE THREAD

**Issue by minimallinux** [franciscop/picnic#167]
Hi, I just built a header/nav for the page using your demo, it works great but I can't get any content to show on the page below it. It appears right at top of the nav/header. I've tried sections, containers etc but nothing works. Is this something to do with the resets? I am using picnic.css from the root folder. Thanks

**Comment by franciscop** [comment]
That is true, if you add the nav and in its fixed default position you'll have to add padding-top to the body or html. However, since the nav height can be variable AND you might not even include a nav, I leave that decision up to the devs since I don't want to mess with body's padding.

```css
body {
  padding-top: 3em;
}
```

If that's not the issue, please feel free to reopen but add some code/jsfiddle example where I can see the issue.
