### ISSUE TITLE
Modularity is lacking

### ISSUE THREAD

**Issue by liko28s** [franciscop/picnic#172]
Hello guys, I suggest that for future versions of picnic.css emphasis is placed on modularity, currently you can not use picnic components without including everything, for example, if you want to use the navbar
```
@import 'BOWER_PATH/picnic/src/picnic';
@import 'BOWER_PATH/picnic/plugins/nav/plugin';
```

but here everything is included (i.e button, links etc)
`@import 'BOWER_PATH/picnic/src/picnic';`

Ideally, ONLY the nav functionality and styles should be included when importing.
`@import 'BOWER_PATH/picnic/plugins/nav/plugin';`

**Comment by franciscop** [comment]
Hi @liko28s, thanks for the request. I agree, better modularity could be achieved. However, you *can* include the nav in the way you want it without including everything else! It is not be properly documented since that wasn't such a big usercase back when I made the docs, but now I use it like that a lot:

```scss
@import 'BOWER_PATH/picnic/src/themes/default/theme';
@import 'BOWER_PATH/picnic/src/plugins/nav/plugin';
```

You do have to include the theme though, but that doesn't export anything (just used for declaring variables).
