### ISSUE TITLE
[feature request] sidebar navigation

### ISSUE THREAD

**Issue by gittus** [franciscop/picnic#181]
Hi,

to have more flexibility in using picnic in various projects/layouts it would be really helpful to have the possibility to decide whether the fix part of the navigation bar should be in horizontal (on top) or vertical (as sidebar) alignment.
Today it is "only" in horizontal alignment and this limits the layout unnecessarily.

P.S. Maybe somebody can provide a css snippet for a vertical alignment which fits to the current picnic.css.

**Comment by franciscop** [comment]
Hi @gittus, thanks for the feature request. I am not sure what you mean, but it seems you are asking for a totally different alternative way for the navbar to work. Unfortunately this will not happen in Picnic but you can always extend it with your own CSS.

Otherwise, it seems you are asking for people to write a significant piece of code for you for free. While developers might do it, these kind of requests are normally discouraged in any of the programming communities I know (Github, Stackoverflow, Reddit, etc).

**Comment by gittus** [comment]
Hi @franciscop,

I think, you have me complete misunderstood. 
No, this is not totally different. Sorry for confusing description. So I'll try it again:

Today the _fix_ part of the navigation is like:
-------------------------------------------------------------------
                                                         menu    menu    menu
-------------------------------------------------------------------
    content
    content
    ...
This is horizontal aligned.

My ask was to offer also a vertical aligned _fix_ part of the navigation like:
menu    | content
menu    | content
menu    | ...
             | 
             | 

The behaviour of the hamburger menu (dynamic part) etc. is exact the same (except the side of visualisation).
I hope this description is more clear now. ;)


P.S. I did not ask for writing a "significant piece of code for you for free" as I think, this are just some lines and maybe somebody has this already. I'm not so familar with CSS.
