### ISSUE TITLE
CSS file size of 41KB (announced 10KB)

### ISSUE THREAD

**Issue by henricazottes** [franciscop/picnic#192]
Hi, I'm looking for a very lightwight css library and on your homepage you were talking about being under 10KB (awesome!). Checking the network is kinda different though... I only see 41KB :/

How do you get the 10KB result?

**Comment by franciscop** [comment]
The 41kb you are seeing is the **raw size** of **the website**, which is **not** the Picnic CSS library:

<img width="630" alt="Screen Shot 2019-05-14 at 0 53 31" src="https://user-images.githubusercontent.com/2801252/57635744-b9b1b280-75e2-11e9-9f58-6fc2f03abdcb.png">

For [the latest Library file](https://cdn.jsdelivr.net/npm/picnic@6.5.0/picnic.min.css) you can see it's 7.8kb compressed (38kb raw):

<img width="629" alt="Screen Shot 2019-05-14 at 0 55 34" src="https://user-images.githubusercontent.com/2801252/57635931-29c03880-75e3-11e9-8e6a-317d3787fac6.png">

Since what is transmitted is the compressed file, this is what is reported as the official size in basically all libraries. So yeah, Picnic CSS is `7.77kb` at the time of this writing, I put it as `under 10kb` so I didn't have to worry about small changes in the overall size.
